{% set name = "labelme" %}
{% set version = "4.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: febd7aaee7251e93b675bb5116127efe9a516d03f701d7326b2df697f4ef4dfb
  # patches:
  #   - disable_automatic_install_of_qt.patch

build:
  number: 0
  # too lazy to build python 2.7 for an interactive tool
  skip: true  # [py==27]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - labelme = labelme.__main__:main
    - labelme_draw_json = labelme.cli.draw_json:main
    - labelme_draw_label_png = labelme.cli.draw_label_png:main
    - labelme_json_to_dataset = labelme.cli.json_to_dataset:main
  osx_is_app: true

requirements:
  host:
    - python
    - pip
  run:
    - python
    - imgviz >=0.10.2
    - matplotlib-base
    - numpy
    - pillow
    - pyyaml
    - termcolor
    - qtpy

test:
  requires:
    - pyqt
  commands:
    - labelme --help

app:
  entry: labelme
  icon: {{ SRC_DIR }}/labelme/icons/icon.png
  summary: Image Polygonal Annotation with Python
  type: desk

about:
  home: https://github.com/wkentaro/labelme
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Image Polygonal Annotation with Python (polygon, rectangle, circle, line, point and image-level flag annotation).
  description: |
    Labelme is a graphical image annotation tool inspired by http://labelme.csail.mit.edu.
    It is written in Python and uses Qt for its graphical interface.

extra:
  recipe-maintainers:
    - hmaarrfk
