{% set name = "labelme" %}
{% set version = "5.4.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2399a0b16022b044a6778ace72851903c1bcecb81838a8479b616e19a369f81a
  patches:
    # The user may have installed either pyside2 or qtpy
    # just let them decide
    - do_not_add_qt_to_pip_depencnies.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - labelme = labelme.__main__:main
    - labelme_draw_json = labelme.cli.draw_json:main
    - labelme_draw_label_png = labelme.cli.draw_label_png:main
    - labelme_json_to_dataset = labelme.cli.json_to_dataset:main
  osx_is_app: true

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - natsort
    - imgviz >=0.11.0
    - matplotlib-base
    - numpy
    - pillow >=2.8.0
    - pyyaml
    - termcolor
    - qtpy
    - colorama

test:
  requires:
    - pyside2
    - pip
  commands:
    - labelme --help
    - pip check

app:
  entry: labelme
  icon: {{ SRC_DIR }}/labelme/icons/icon.png
  summary: Image Polygonal Annotation with Python
  type: desk

about:
  home: https://github.com/wkentaro/labelme
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Image Polygonal Annotation with Python (polygon, rectangle, circle, line, point and image-level flag annotation).
  description: |
    Labelme is a graphical image annotation tool inspired by http://labelme.csail.mit.edu.
    It is written in Python and uses Qt for its graphical interface.

extra:
  recipe-maintainers:
    - hmaarrfk
